version: "2"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - "./frontend/app:/app"
      - "/app/node_modules"
    tty: true
    ports:
      - "4000:5173"

  backend:
    container_name: backend
    build: ./backend
    tty: true
    volumes:
      - "./backend/app:/app"
      - "/app/vendor"
    ports:
      - 3000:8000

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
        - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data:
    driver: local