version: "2"

services:
  lms:
    build: .
    volumes:
      - "./:/lms"
      - "/lms/laravel/vendor"
      - "/lms/laravel/node_modules"
    ports:
      - 3000:8000

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
        - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  db_data:
    driver: local